// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfe6S04Cf2v7VppZmCmBGwGnyHZ03tR4',
    appId: '1:909498412571:web:4b602064136a483e1292be',
    messagingSenderId: '909498412571',
    projectId: 'myfirebaseapp-37c92',
    authDomain: 'myfirebaseapp-37c92.firebaseapp.com',
    storageBucket: 'myfirebaseapp-37c92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xtg7EbCt0gjYv0MKDTD_rZaJSBW5e1g',
    appId: '1:909498412571:android:7830523425d5007a1292be',
    messagingSenderId: '909498412571',
    projectId: 'myfirebaseapp-37c92',
    storageBucket: 'myfirebaseapp-37c92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD43RDbkKNsKFFwUZJDzscFPQQM6Kv0DpE',
    appId: '1:909498412571:ios:673b3a539363361b1292be',
    messagingSenderId: '909498412571',
    projectId: 'myfirebaseapp-37c92',
    storageBucket: 'myfirebaseapp-37c92.firebasestorage.app',
    iosBundleId: 'com.example.pushnotificationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD43RDbkKNsKFFwUZJDzscFPQQM6Kv0DpE',
    appId: '1:909498412571:ios:673b3a539363361b1292be',
    messagingSenderId: '909498412571',
    projectId: 'myfirebaseapp-37c92',
    storageBucket: 'myfirebaseapp-37c92.firebasestorage.app',
    iosBundleId: 'com.example.pushnotificationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwfe6S04Cf2v7VppZmCmBGwGnyHZ03tR4',
    appId: '1:909498412571:web:ebc9b24476d5d9fc1292be',
    messagingSenderId: '909498412571',
    projectId: 'myfirebaseapp-37c92',
    authDomain: 'myfirebaseapp-37c92.firebaseapp.com',
    storageBucket: 'myfirebaseapp-37c92.firebasestorage.app',
  );
}
